Headers and license
CCSI-Toolset/Packed_Column_Gen pull request #2
Opened 2024-02-29 15:39 UTC by ygshah

Made changes to the license file and headers in the python file, so the license is not copied over to each file.

2024-03-06 22:23 UTC, ksbeattie requested changes

2024-03-06 22:23 UTC, ksbeattie commented on InitGui.py~
This is a backup file and shouldn't be included here.

2024-03-06 22:23 UTC, ksbeattie commented on columnGen/__init__.py
> +# ***************************************************************************
I don't think this is really needed in a `__init__.py` file, but should at least be shorted, as done in some of the other files, to just refer to the `LICENSE.md` file.

2024-03-06 22:23 UTC, ksbeattie commented on columnGen/commands.py
> +from .preamble import *
No ref to LICENSE.md?

2024-03-06 22:23 UTC, ksbeattie commented on packedColumnGen.exe
I'm guessing this shouldn't be here either...

2024-03-06 22:23 UTC, ksbeattie commented on README.html
This looks like a duplicate of the README.md file?  If so, is it needed?

2024-03-06 22:23 UTC, ksbeattie commented on columnTree.png
This looks like it might be in the wrong place here at the top-level?

2024-03-06 22:23 UTC, ksbeattie commented on doc/User_Guide.html
This looks like a duplicate of the README.md file?

2024-03-13 19:57 UTC, ygshah commented on InitGui.py~
Thanks for catching this and other issues! Fixed this in the most recent commit and will submit another merge request.

2024-03-13 19:57 UTC, ygshah commented on columnGen/__init__.py
> +# ***************************************************************************
Fixed this in the most recent commit.

2024-03-13 19:58 UTC, ygshah commented on columnGen/commands.py
> +from .preamble import *
The short reference is added in the most recent commit. Thanks for catching this!

2024-03-13 19:58 UTC, ygshah commented on packedColumnGen.exe
Removed the executable file.

2024-03-13 19:59 UTC, ygshah commented on README.html
Removed the html version. Git automatically displays the markdown files in a nice format, so the html file is not really needed here.

2024-03-13 20:00 UTC, ygshah commented on columnTree.png
Removed this file.

2024-03-13 20:01 UTC, ygshah commented on doc/User_Guide.html
This is separate from the README file. It has some instructions on getting started with the tool, so I have retained the file in the most recent commit.

2024-03-13 20:02 UTC, ygshah commented
Made changes into the most recent commit.

2025-01-08 16:32 UTC, ksbeattie approved these changes
Not a fan of the wildcard imports, but this looks ok for now.

2025-01-08 16:33 UTC, merged